# Windows 10下开源项目finrobot的conda环境配置
name: finrobot_dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  # 二进制依赖（精确到 setup.py/requirements.txt 里 pin 的版本）
  - numpy=1.26.4
  - pandas=2.0.3
  - requests=2.31.0
  - scikit-learn=1.5.0
  - starlette=0.37.2
  - tenacity=8.3.0
  - tqdm=4.66.1
  - typing-extensions=4.9.0
  - aiohttp=3.8.5
  - matplotlib
  - nltk=3.8.1
  - pandas-datareader
  - pip
  # 纯 Python 包交给 pip 安装
  # 第一行的 -e . 是通过-e(editable)的方式来安装当前目录下的包（finrobot）
  - pip:
    - -e .
    - pyautogen[retrievechat]>=0.2.19
    - finnhub-python
    - backtrader
    - langchain==0.1.20
    - marker-pdf
    - mplfinance
    - pdfkit==1.0.0
    - praw
    - pyPDF2
    - ratelimit==2.2.1
    - reportlab
    - sec-api
    - tushare
    - unstructured==0.8.1
    - yfinance
    - anthropic
    - google-genai
    - openai
    - python-magic
    - python-magic-bin
    - ipykernel
